class ErroDeConta (Exception):
    ...

class LimiteExcedidoError (ErroDeConta):
    ...

class SaldoInsuficienteError (ErroDeConta):
    ... 

class ValorInvalidoError (ErroDeConta):
    ... 

class OpcaoInvalidaError (ErroDeConta):
    ...